version: '3'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - test_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION=TestOrg
      - LDAP_DOMAIN=test.org
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=config
      - LDAP_TLS_VERIFY_CLIENT=never
      - LDAP_SEED_INTERNAL_LDIF_PATH=/home/ldif
    volumes:
      - ./users.ldif:/home/ldif/users.ldif
    command: --loglevel debug
    ports:
      - "389:389"
      - "636:636"
    networks:
      - test_network

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "8080:80"
    depends_on:
      - openldap
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
